#!/bin/sh

### BEGIN INIT INFO
# Provides:          Khresmoi
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Khresmoi MT services
# Description:       Khresmoi MT services (Moses server + worker).
### END INIT INFO

# Khresmoi init script

# the user to run this script
USER=khresmoi
VERSION=stable
KHRESMOI_INIT=/etc/init.d/khresmoi

# Check if we run as the designated user
case "`whoami`" in
    ${USER}) # OK, run
        ;;
    root)  # relaunch using su -
        exec su --login $USER -c "$KHRESMOI_INIT $@"
        ;;
    *)  # die
        echo "Must be run as root or $USER. Aborting."
        exit 1
        ;;
esac

# Wait for NFS share to be accessible, return success status
wait_for_nfs() {
    CTR=50
    while [ $CTR -gt 0 ]; do
        if [ -d ~/mt-$VERSION/scripts ]; then
            return 0
        fi
        sleep 5
        CTR=`expr $CTR - 1`
    done
    return 1
}

# Start the Khresmoi service
start() {
    echo `date` "Waiting for NFS..." >> /var/log/khresmoi/startup_worker.log
    wait_for_nfs || { echo `date` "Timeout." >> /var/log/khresmoi/startup_worker.log; exit 1; }

    echo `date` "Starting Khresmoi services using init scripts..." | tee -a ~/mt-$VERSION/logs/autorun.log
    echo "Running as user $USER: ~/mt-$VERSION/scripts/run_{worker,moses}" | tee -a ~/mt-$VERSION/logs/autorun.log

    echo `date` "Khresmoi startup PHASE1: user $USER: ~/mt-$VERSION/scripts/run_worker..." | tee -a ~/mt-$VERSION/logs/autorun.log
    nohup ~/mt-$VERSION/scripts/run_worker >> /var/log/khresmoi/startup_worker.log 2>&1 &

    echo `date` "Khresmoi startup PHASE2: user $USER: ~/mt-$VERSION/scripts/run_moses..." | tee -a ~/mt-$VERSION/logs/autorun.log
    nohup ~/mt-$VERSION/scripts/run_moses >> /var/log/khresmoi/startup_moses.log 2>&1 &
}

# Stop the Khresmoi service
stop() {
    echo `date` "Stopping Khresmoi services using init script..." | tee -a ~/mt-$VERSION/logs/autorun.log
    for i in `ps ax | grep -E "(mosess[e]rver.*$VERSION|$VERSION.*/worker\.py)" | sed 's/^\s*\([0-9]\+\)\s.*/\1/'`; do
        kill $i; 
    done
}

status() {
    echo "Khresmoi init - khresmoi user proccess list:"
    ps -u khresmoi
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
