#!/bin/sh

. ~khresmoi/mt-stable/scripts/moses_setenv.sh
. ~khresmoi/mt-stable/config/config_moses.sh

cd $MODELS_DIR
nohup mosesserver --server-port $RECASER_PORT -f $RECASER_INI >> ~khresmoi/mt-stable/logs/recaser.log 2>&1 &
mosesserver --server-port $TRANSL_PORT  -f $TRANSL_INI >> ~khresmoi/mt-stable/logs/translate.log 2>&1 &
