#!/bin/bash
#
# Run worker with correct logging and DB setting.
#
# Usage: sudo -u khresmoi run_worker [-r]
#
# -r = Force restart
#

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && dirname `pwd` )"
USERHOME=`dirname $BASEDIR`
VERSION=`basename $BASEDIR`

if [ "$1" == '-r' ]; then
    echo "Killing existing worker..."
    for i in `ps ax | grep "$VERSION.*/worker\.py" | sed 's/^\s*\([0-9]\+\)\s.*/\1/'`; do 
        echo $i;
        kill $i; 
    done
    sleep 2
fi

. $USERHOME/virtualenv/bin/activate
. $BASEDIR/config/config_worker.sh
WORKER_PORT=`cat $MICROTASK_SETTINGS | grep 'PORT' | sed s'/[^0-9]//g'`

cd $BASEDIR/logs
nohup python $BASEDIR/worker/worker.py >> $BASEDIR/logs/worker.log 2>&1 &

until nc -z localhost $WORKER_PORT; do
    sleep 2;
done

