#!/bin/bash
#
# Run Appserver with correct logging and DB setting.
#
# Usage: sudo -u khresmoi run_appserver [-r]
#
# -r = Force restart
#

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && dirname `pwd` )"
USERHOME=`dirname $BASEDIR`
VERSION=`basename $BASEDIR`

if [ "$1" == '-r' ]; then
    echo "Killing existing Appserver..."
    for i in `ps ax | grep "$VERSION.*/appserver\.py" | sed 's/^\s*\([0-9]\+\)\s.*/\1/'`; do 
        kill $i; 
    done
    sleep 5
fi

. $USERHOME/virtualenv/bin/activate

cd $BASEDIR/logs
nohup python $BASEDIR/appserver/appserver.py -c $BASEDIR/config/appserver.cfg >> $BASEDIR/logs/appserver.log 2>&1 &
