#!/bin/sh

. ~khresmoi/scripts-stable/moses_setenv.sh
. ~khresmoi/config-stable/config_moses.sh

cd $MODELS_DIR
#mosesserver --server-port $RECASER_PORT -f $RECASER_INI &
mosesserver --server-port $TRANSL_PORT  -f $TRANSL_INI
